// generated by stringer -type=DiffSource diff_source.go; DO NOT EDIT

package terraform

import "fmt"

const (
	_DiffSource_name_0 = "DiffSourceUnset"
	_DiffSource_name_1 = "DiffSourceConfig"
	_DiffSource_name_2 = "DiffSourceState"
)

var (
	_DiffSource_index_0 = [...]uint8{0, 15}
	_DiffSource_index_1 = [...]uint8{0, 16}
	_DiffSource_index_2 = [...]uint8{0, 15}
)

func (i DiffSource) String() string {
	switch {
	case i == 0:
		return _DiffSource_name_0
	case i == 2:
		return _DiffSource_name_1
	case i == 4:
		return _DiffSource_name_2
	default:
		return fmt.Sprintf("DiffSource(%d)", i)
	}
}
